# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NetEase\Documents\workspace\MusicPlayer\src\ui\main.ui'
#
# Created: Fri Nov 29 21:11:07 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.setWindowModality(QtCore.Qt.NonModal)
        MainWidget.resize(300, 405)
        MainWidget.setWindowTitle(_fromUtf8(""))
        MainWidget.setAutoFillBackground(True)
        self.header = QtGui.QWidget(MainWidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 300, 30))
        self.header.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.header.setObjectName(_fromUtf8("header"))
        self.btnClose = QtGui.QPushButton(self.header)
        self.btnClose.setGeometry(QtCore.QRect(280, 7, 16, 16))
        self.btnClose.setAutoFillBackground(False)
        self.btnClose.setStyleSheet(_fromUtf8("background: url(:/button/close) no-repeat;border:none"))
        self.btnClose.setText(_fromUtf8(""))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnMenu = QtGui.QPushButton(self.header)
        self.btnMenu.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.btnMenu.setAutoFillBackground(False)
        self.btnMenu.setStyleSheet(_fromUtf8("background: url(:/button/title.jpg) no-repeat;border:none"))
        self.btnMenu.setText(_fromUtf8(""))
        self.btnMenu.setIconSize(QtCore.QSize(20, 20))
        self.btnMenu.setObjectName(_fromUtf8("btnMenu"))
        self.listSongs = QtGui.QListWidget(MainWidget)
        self.listSongs.setGeometry(QtCore.QRect(5, 145, 290, 225))
        self.listSongs.setObjectName(_fromUtf8("listSongs"))
        self.middle = QtGui.QWidget(MainWidget)
        self.middle.setGeometry(QtCore.QRect(0, 30, 300, 110))
        self.middle.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.middle.setObjectName(_fromUtf8("middle"))
        self.cover = QtGui.QWidget(self.middle)
        self.cover.setGeometry(QtCore.QRect(10, 5, 100, 100))
        self.cover.setStyleSheet(_fromUtf8("background:url(:/logo/logo.png)"))
        self.cover.setObjectName(_fromUtf8("cover"))
        self.name = QtGui.QLabel(self.middle)
        self.name.setGeometry(QtCore.QRect(120, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.author = QtGui.QLabel(self.middle)
        self.author.setGeometry(QtCore.QRect(120, 31, 171, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(237, 131, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 131, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.author.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.author.setFont(font)
        self.author.setTextFormat(QtCore.Qt.RichText)
        self.author.setObjectName(_fromUtf8("author"))
        self.btnStart = QtGui.QPushButton(self.middle)
        self.btnStart.setGeometry(QtCore.QRect(180, 70, 20, 15))
        self.btnStart.setStyleSheet(_fromUtf8("QPushButton#btnStart {border:none;background: url(:/button/btnStart.jpg);}"))
        self.btnStart.setText(_fromUtf8(""))
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.btnRewind = QtGui.QPushButton(self.middle)
        self.btnRewind.setGeometry(QtCore.QRect(150, 70, 20, 15))
        self.btnRewind.setAutoFillBackground(False)
        self.btnRewind.setStyleSheet(_fromUtf8("QPushButton#btnRewind {border:none;background: url(:/button/btnRewind.jpg);}\n"
""))
        self.btnRewind.setText(_fromUtf8(""))
        self.btnRewind.setObjectName(_fromUtf8("btnRewind"))
        self.btnForward = QtGui.QPushButton(self.middle)
        self.btnForward.setGeometry(QtCore.QRect(240, 70, 20, 15))
        self.btnForward.setStyleSheet(_fromUtf8("QPushButton#btnForward {border:none;background: url(:/button/btnForward.jpg);}"))
        self.btnForward.setText(_fromUtf8(""))
        self.btnForward.setObjectName(_fromUtf8("btnForward"))
        self.btnReset = QtGui.QPushButton(self.middle)
        self.btnReset.setGeometry(QtCore.QRect(210, 70, 20, 15))
        self.btnReset.setStyleSheet(_fromUtf8("QPushButton#btnReset {border:none;background: url(:/button/btnReset.jpg);}"))
        self.btnReset.setText(_fromUtf8(""))
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.horizontalSlider = QtGui.QSlider(self.middle)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 90, 171, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.consumeTime = QtGui.QLabel(self.middle)
        self.consumeTime.setGeometry(QtCore.QRect(120, 70, 25, 15))
        self.consumeTime.setObjectName(_fromUtf8("consumeTime"))
        self.totalTime = QtGui.QLabel(self.middle)
        self.totalTime.setGeometry(QtCore.QRect(270, 70, 25, 15))
        self.totalTime.setObjectName(_fromUtf8("totalTime"))
        self.seperator1 = QtGui.QWidget(MainWidget)
        self.seperator1.setGeometry(QtCore.QRect(0, 30, 300, 1))
        self.seperator1.setStyleSheet(_fromUtf8("background:rgb(234,234,234)"))
        self.seperator1.setObjectName(_fromUtf8("seperator1"))
        self.footer = QtGui.QWidget(MainWidget)
        self.footer.setGeometry(QtCore.QRect(0, 370, 300, 35))
        self.footer.setStyleSheet(_fromUtf8("background: url(:/background/footerBg.jpg);"))
        self.footer.setObjectName(_fromUtf8("footer"))
        self.btnRepeat = QtGui.QPushButton(self.footer)
        self.btnRepeat.setGeometry(QtCore.QRect(260, 5, 40, 25))
        self.btnRepeat.setStyleSheet(_fromUtf8("QPushButton#btnRepeat {border:none;background: url(:/button/btnRepeat.jpg) no-repeat;}"))
        self.btnRepeat.setText(_fromUtf8(""))
        self.btnRepeat.setIconSize(QtCore.QSize(18, 18))
        self.btnRepeat.setObjectName(_fromUtf8("btnRepeat"))
        self.btnShuffle = QtGui.QPushButton(self.footer)
        self.btnShuffle.setGeometry(QtCore.QRect(220, 5, 40, 25))
        self.btnShuffle.setStyleSheet(_fromUtf8("QPushButton#btnShuffle {border:none;background: url(:/button/btnShuffle.jpg);}"))
        self.btnShuffle.setText(_fromUtf8(""))
        self.btnShuffle.setObjectName(_fromUtf8("btnShuffle"))
        self.horizontalSlider_2 = QtGui.QSlider(self.footer)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(50, 8, 131, 20))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label = QtGui.QLabel(self.footer)
        self.label.setGeometry(QtCore.QRect(10, 8, 31, 20))
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        self.name.setText(_translate("MainWidget", "PLAYER", None))
        self.author.setText(_translate("MainWidget", "capsule", None))
        self.consumeTime.setText(_translate("MainWidget", "3:46", None))
        self.totalTime.setText(_translate("MainWidget", "4:03", None))
        self.label.setText(_translate("MainWidget", "音量", None))

import assets_rc
